# Generated by Django 6.0.8 on 2026-09-10 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de negocio',
                'verbose_name_plural': 'Unidades de negocio',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=60)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('parcial', 'Parcial')], default='ok', max_length=10)),
                ('mensaje', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='GpsPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=30)),
                ('dia_utc', models.DateField()),
                ('puntos', models.JSONField(default=list)),
            ],
            options={
                'unique_together': {('car', 'dia_utc')},
            },
        ),
        migrations.CreateModel(
            name='GrupoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=180, unique=True)),
                ('gcode', models.CharField(blank=True, max_length=60)),
                ('plant_key', models.CharField(blank=True, max_length=20)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='core.businessunit')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Grupo de cliente',
                'verbose_name_plural': 'Grupos de cliente',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_admin', models.BooleanField(default=False, help_text='Acceso total a todos los clientes y plazas.')),
                ('clientes', models.ManyToManyField(blank=True, related_name='usuarios', to='core.cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'ordering': ['year', 'week'],
                'unique_together': {('year', 'week')},
            },
        ),
        migrations.CreateModel(
            name='MaeRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_seq', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('shift', models.CharField(blank=True, max_length=5)),
                ('route_type', models.CharField(blank=True, max_length=5)),
                ('quality', models.FloatField(blank=True, null=True)),
                ('history_size', models.IntegerField(default=0)),
                ('n_stops', models.IntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='core.grupocliente')),
            ],
            options={
                'unique_together': {('grupo', 'ruta_seq')},
            },
        ),
        migrations.CreateModel(
            name='CRRutaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_seq', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('shift', models.CharField(blank=True, max_length=5)),
                ('route_type', models.CharField(blank=True, max_length=5)),
                ('window_mode', models.CharField(choices=[('14d', '14 días'), ('7d', 'Semana')], default='14d', max_length=5)),
                ('criterio', models.CharField(default='done+etaTS', max_length=40)),
                ('calidad', models.FloatField(blank=True, null=True)),
                ('servicios', models.IntegerField(default=0)),
                ('source', models.CharField(default='api', max_length=10)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_rutas', to='core.grupocliente')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_rutas', to='core.semana')),
            ],
            options={
                'indexes': [models.Index(fields=['semana', 'window_mode'], name='core_crruta_semana__332ae1_idx')],
                'unique_together': {('grupo', 'semana', 'ruta_seq', 'window_mode')},
            },
        ),
        migrations.CreateModel(
            name='CRClienteSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_mode', models.CharField(default='14d', max_length=5)),
                ('calidad', models.FloatField(blank=True, null=True)),
                ('rutas', models.IntegerField(default=0)),
                ('source', models.CharField(default='api', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr', to='core.cliente')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr', to='core.semana')),
            ],
            options={
                'indexes': [models.Index(fields=['semana', 'window_mode'], name='core_crclie_semana__49db86_idx')],
                'unique_together': {('cliente', 'semana', 'window_mode')},
            },
        ),
        migrations.CreateModel(
            name='ViajeSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('entradas', models.IntegerField(default=0)),
                ('retrasos', models.IntegerField(default=0)),
                ('ns', models.FloatField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='core.cliente')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='core.semana')),
            ],
            options={
                'unique_together': {('cliente', 'semana')},
            },
        ),
    ]
