# Generated by Django 6.0.8 on 2026-09-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefinamientoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_seq', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('tol_m', models.PositiveIntegerField(default=200, help_text='Tolerancia en metros (plataforma: 200).')),
                ('ventana_min', models.PositiveIntegerField(blank=True, help_text='Minutos alrededor de la parada. Vacío = todo el servicio.', null=True)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refinamientos', to='core.grupocliente')),
            ],
            options={
                'verbose_name': 'Refinamiento GPS',
                'verbose_name_plural': 'Refinamientos GPS',
                'unique_together': {('grupo', 'ruta_seq')},
            },
        ),
    ]
