# Generated by Django 6.0.8 on 2026-09-23 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_refinamientoruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaIndicadoresSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_seq', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('servicios', models.IntegerField(default=0)),
                ('entradas', models.IntegerField(default=0)),
                ('retrasos', models.IntegerField(default=0)),
                ('ns', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='api', max_length=10)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_indicadores', to='core.businessunit')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_indicadores', to='core.grupocliente')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_indicadores', to='core.semana')),
            ],
            options={
                'verbose_name': 'Indicadores por ruta',
                'verbose_name_plural': 'Indicadores por ruta',
                'indexes': [models.Index(fields=['business_unit', 'semana'], name='core_rutain_busines_e69d19_idx')],
                'unique_together': {('business_unit', 'semana', 'grupo', 'ruta_seq')},
            },
        ),
        migrations.CreateModel(
            name='ServicioRutaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=40)),
                ('service_id', models.CharField(blank=True, max_length=60)),
                ('ruta_seq', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('car', models.CharField(blank=True, max_length=30)),
                ('operador', models.CharField(blank=True, max_length=120)),
                ('nomina', models.CharField(blank=True, max_length=40)),
                ('prog_ini', models.TimeField(blank=True, null=True)),
                ('real_ini', models.TimeField(blank=True, null=True)),
                ('dif_ini', models.IntegerField(blank=True, null=True)),
                ('prog_fin', models.TimeField(blank=True, null=True)),
                ('real_fin', models.TimeField(blank=True, null=True)),
                ('dif_fin', models.IntegerField(blank=True, null=True)),
                ('diagnostico_inicio', models.CharField(blank=True, max_length=20)),
                ('diagnostico_viaje', models.CharField(blank=True, max_length=80)),
                ('estado_viaje', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(blank=True, max_length=5)),
                ('tipo_viaje', models.CharField(blank=True, max_length=5)),
                ('shift', models.CharField(blank=True, max_length=5)),
                ('record_quality', models.CharField(blank=True, max_length=5)),
                ('es_entrada', models.BooleanField(default=False)),
                ('es_retraso', models.BooleanField(default=False)),
                ('source', models.CharField(default='api', max_length=10)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='core.businessunit')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='core.grupocliente')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='core.semana')),
            ],
            options={
                'verbose_name': 'Servicio de ruta',
                'verbose_name_plural': 'Servicios de ruta',
                'indexes': [models.Index(fields=['business_unit', 'semana', 'ruta_seq'], name='core_servic_busines_a56f2b_idx'), models.Index(fields=['business_unit', 'semana', 'es_retraso'], name='core_servic_busines_edc87a_idx')],
                'unique_together': {('business_unit', 'semana', 'external_id')},
            },
        ),
    ]
