# Generated by Django 6.0.8 on 2026-09-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rutaindicadoressemana_serviciorutasemana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciorutasemana',
            name='car',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
