# Generated by Django 6.0.8 on 2026-09-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_serviciorutasemana_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='business_units',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.businessunit'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='correos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
    ]
