# Generated by Django 6.0.8 on 2026-09-24 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfil_datos_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParadaRutaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_seq', models.CharField(max_length=20)),
                ('stop_id', models.CharField(max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('window_mode', models.CharField(default='7d', max_length=5)),
                ('servicios', models.IntegerField(default=0)),
                ('detectadas', models.IntegerField(default=0)),
                ('calidad', models.FloatField(blank=True, null=True)),
                ('ultima_deteccion', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='api', max_length=10)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parada por ruta',
                'verbose_name_plural': 'Paradas por ruta',
            },
        ),
        migrations.RemoveIndex(
            model_name='rutaindicadoressemana',
            name='core_rutain_busines_e69d19_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rutaindicadoressemana',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rutaindicadoressemana',
            name='window_mode',
            field=models.CharField(default='7d', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='rutaindicadoressemana',
            unique_together={('business_unit', 'semana', 'grupo', 'ruta_seq', 'window_mode')},
        ),
        migrations.AddIndex(
            model_name='rutaindicadoressemana',
            index=models.Index(fields=['business_unit', 'semana', 'window_mode'], name='core_rutain_busines_88100d_idx'),
        ),
        migrations.AddField(
            model_name='paradarutasemana',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_ruta', to='core.businessunit'),
        ),
        migrations.AddField(
            model_name='paradarutasemana',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_ruta', to='core.grupocliente'),
        ),
        migrations.AddField(
            model_name='paradarutasemana',
            name='semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_ruta', to='core.semana'),
        ),
        migrations.AddIndex(
            model_name='paradarutasemana',
            index=models.Index(fields=['business_unit', 'semana', 'ruta_seq', 'window_mode'], name='core_parada_busines_1255db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paradarutasemana',
            unique_together={('business_unit', 'semana', 'ruta_seq', 'stop_id', 'window_mode')},
        ),
    ]
