# Generated by Django 6.0.8 on 2026-09-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paradarutasemana_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paradarutasemana',
            unique_together={('business_unit', 'semana', 'grupo', 'ruta_seq', 'stop_id', 'window_mode')},
        ),
    ]
