# Generated by Django 6.0.8 on 2026-10-06 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paradarutasemana_servicios_gps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.businessunit')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.cliente')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.semana')),
            ],
            options={
                'verbose_name': 'Comentario de semana',
                'verbose_name_plural': 'Comentarios de semana',
                'ordering': ['creado'],
                'indexes': [models.Index(fields=['cliente', 'business_unit', 'semana'], name='core_coment_cliente_49e37d_idx')],
            },
        ),
    ]
