# Generated by Django 6.0.9 on 2026-10-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_viajesemana_crclientesemana_business_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupocliente',
            name='group',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterUniqueTogether(
            name='grupocliente',
            unique_together={('group', 'business_unit')},
        ),
    ]
